const axios = require('axios');

// Function to place an order
async function placeOrder(symbol, quantity, transactionType) {
    const data = JSON.stringify({
        "exchange": "NSE",
        "tradingsymbol": symbol,
        "quantity": quantity,
        "transactiontype": transactionType,
        "ordertype": "MARKET",
        "variety": "NORMAL",
        "producttype": "INTRADAY"
    });

    const config = {
        method: 'post',
        url: 'https://apiconnect.angelbroking.com/rest/secure/angelbroking/order/v1/placeOrder',
        headers: {
            'Authorization': 'Bearer AUTHORIZATION_TOKEN',
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'X-UserType': 'USER',
            'X-SourceID': 'WEB',
            'X-ClientLocalIP': '192.168.168.168',
            'X-ClientPublicIP': '106.193.147.98',
            'X-MACAddress': 'fe80::216e:6507:4b90:3719',
            'X-PrivateKey': 'dTd8R04O '
        },
        data: data
    };

    try {
        const response = await axios(config);
        console.log(JSON.stringify(response.data));
    } catch (error) {
        console.log(error);
    }
}

// Example usage:
// Assume symbol, quantity, and transactionType are passed from the main strategy function
const symbol = 'INFY-EQ'; // Example symbol
const quantity = 5; // Example quantity
const transactionType = 'BUY'; // Example transaction type ('BUY' or 'SELL')

// Call placeOrder based on signals generated by the strategy
placeOrder(symbol, quantity, transactionType);
